spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Passw0rd
    url: jdbc:mysql://47.98.112.246:3306/springcloud_sell?characterEncoding=utf8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest

debug: true
